### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by uselesswaifu** [ZeroDevOfficial/Aether#16]
Why'd you pull a me

**Comment by ZeroDevOfficial** [comment]
@uselesswaifu I dont want the core anymore, I feel that if anyone finds useful code they can have it. im not asking for people to continue it, more they can take the core and use it for what they want

**Comment by uselesswaifu** [comment]
#BringAetherBack

**Comment by ZeroDevOfficial** [comment]
#LetAetherDie #onlyAetherMinecraftDiesTonight
